//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jaxwsService.duanzq.com/", ConfigurationName="ServiceReference1.ServiceDemo1Impl")]
    public interface ServiceDemo1Impl {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxwsService.duanzq.com/ServiceDemo1Impl/Test1Request", ReplyAction="http://jaxwsService.duanzq.com/ServiceDemo1Impl/Test1Response")]
        ConsoleApplication2.ServiceReference1.Test1Response Test1(ConsoleApplication2.ServiceReference1.Test1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Test1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test1", Namespace="http://jaxwsService.duanzq.com/", Order=0)]
        public ConsoleApplication2.ServiceReference1.Test1RequestBody Body;
        
        public Test1Request() {
        }
        
        public Test1Request(ConsoleApplication2.ServiceReference1.Test1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Test1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public Test1RequestBody() {
        }
        
        public Test1RequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Test1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test1Response", Namespace="http://jaxwsService.duanzq.com/", Order=0)]
        public ConsoleApplication2.ServiceReference1.Test1ResponseBody Body;
        
        public Test1Response() {
        }
        
        public Test1Response(ConsoleApplication2.ServiceReference1.Test1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Test1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public Test1ResponseBody() {
        }
        
        public Test1ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDemo1ImplChannel : ConsoleApplication2.ServiceReference1.ServiceDemo1Impl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDemo1ImplClient : System.ServiceModel.ClientBase<ConsoleApplication2.ServiceReference1.ServiceDemo1Impl>, ConsoleApplication2.ServiceReference1.ServiceDemo1Impl {
        
        public ServiceDemo1ImplClient() {
        }
        
        public ServiceDemo1ImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDemo1ImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemo1ImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemo1ImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication2.ServiceReference1.Test1Response ConsoleApplication2.ServiceReference1.ServiceDemo1Impl.Test1(ConsoleApplication2.ServiceReference1.Test1Request request) {
            return base.Channel.Test1(request);
        }
        
        public string Test1(string arg0) {
            ConsoleApplication2.ServiceReference1.Test1Request inValue = new ConsoleApplication2.ServiceReference1.Test1Request();
            inValue.Body = new ConsoleApplication2.ServiceReference1.Test1RequestBody();
            inValue.Body.arg0 = arg0;
            ConsoleApplication2.ServiceReference1.Test1Response retVal = ((ConsoleApplication2.ServiceReference1.ServiceDemo1Impl)(this)).Test1(inValue);
            return retVal.Body.@return;
        }
    }
}
