//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class log4net {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("appender", typeof(appender))]
    [System.Xml.Serialization.XmlElementAttribute("logger", typeof(logger))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(param))]
    [System.Xml.Serialization.XmlElementAttribute("renderer", typeof(renderer))]
    [System.Xml.Serialization.XmlElementAttribute("root", typeof(root))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool debug;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(log4netUpdateAttribute.Merge)]
    public log4netUpdateAttribute update;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(log4netLevel.ALL)]
    public log4netLevel threshold;
    
    public log4net() {
        this.debug = false;
        this.update = log4netUpdateAttribute.Merge;
        this.threshold = log4netLevel.ALL;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class appender {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("appendToFile", typeof(appendToFile))]
    [System.Xml.Serialization.XmlElementAttribute("appender-ref", typeof(appender_ref))]
    [System.Xml.Serialization.XmlElementAttribute("applicationName", typeof(applicationName))]
    [System.Xml.Serialization.XmlElementAttribute("authentication", typeof(authentication))]
    [System.Xml.Serialization.XmlElementAttribute("bufferSize", typeof(bufferSize))]
    [System.Xml.Serialization.XmlElementAttribute("commandText", typeof(commandText))]
    [System.Xml.Serialization.XmlElementAttribute("commandType", typeof(commandType))]
    [System.Xml.Serialization.XmlElementAttribute("connectionString", typeof(connectionString))]
    [System.Xml.Serialization.XmlElementAttribute("connectionType", typeof(connectionType))]
    [System.Xml.Serialization.XmlElementAttribute("countDirection", typeof(countDirection))]
    [System.Xml.Serialization.XmlElementAttribute("datePattern", typeof(datePattern))]
    [System.Xml.Serialization.XmlElementAttribute("encoding", typeof(encoding))]
    [System.Xml.Serialization.XmlElementAttribute("evaluator", typeof(evaluator))]
    [System.Xml.Serialization.XmlElementAttribute("facility", typeof(facility))]
    [System.Xml.Serialization.XmlElementAttribute("file", typeof(file))]
    [System.Xml.Serialization.XmlElementAttribute("filter", typeof(filter))]
    [System.Xml.Serialization.XmlElementAttribute("from", typeof(from))]
    [System.Xml.Serialization.XmlElementAttribute("identity", typeof(identity))]
    [System.Xml.Serialization.XmlElementAttribute("immediateFlush", typeof(immediateFlush))]
    [System.Xml.Serialization.XmlElementAttribute("layout", typeof(layout))]
    [System.Xml.Serialization.XmlElementAttribute("localPort", typeof(localPort))]
    [System.Xml.Serialization.XmlElementAttribute("lockingModel", typeof(lockingModel))]
    [System.Xml.Serialization.XmlElementAttribute("logName", typeof(logName))]
    [System.Xml.Serialization.XmlElementAttribute("lossy", typeof(lossy))]
    [System.Xml.Serialization.XmlElementAttribute("machineName", typeof(machineName))]
    [System.Xml.Serialization.XmlElementAttribute("mapping", typeof(mapping))]
    [System.Xml.Serialization.XmlElementAttribute("maxFileSize", typeof(maxFileSize))]
    [System.Xml.Serialization.XmlElementAttribute("maxSizeRollBackups", typeof(maxSizeRollBackups))]
    [System.Xml.Serialization.XmlElementAttribute("maximumFileSize", typeof(maximumFileSize))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(param))]
    [System.Xml.Serialization.XmlElementAttribute("parameter", typeof(parameter))]
    [System.Xml.Serialization.XmlElementAttribute("password", typeof(password))]
    [System.Xml.Serialization.XmlElementAttribute("pickupDir", typeof(pickupDir))]
    [System.Xml.Serialization.XmlElementAttribute("port", typeof(port))]
    [System.Xml.Serialization.XmlElementAttribute("priority", typeof(priority))]
    [System.Xml.Serialization.XmlElementAttribute("recipient", typeof(recipient))]
    [System.Xml.Serialization.XmlElementAttribute("reconnectOnError", typeof(reconnectOnError))]
    [System.Xml.Serialization.XmlElementAttribute("remoteAddress", typeof(remoteAddress))]
    [System.Xml.Serialization.XmlElementAttribute("remotePort", typeof(remotePort))]
    [System.Xml.Serialization.XmlElementAttribute("rollingStyle", typeof(rollingStyle))]
    [System.Xml.Serialization.XmlElementAttribute("securityContext", typeof(securityContext))]
    [System.Xml.Serialization.XmlElementAttribute("sender", typeof(sender))]
    [System.Xml.Serialization.XmlElementAttribute("server", typeof(server))]
    [System.Xml.Serialization.XmlElementAttribute("sink", typeof(sink))]
    [System.Xml.Serialization.XmlElementAttribute("smtpHost", typeof(smtpHost))]
    [System.Xml.Serialization.XmlElementAttribute("staticLogFileName", typeof(staticLogFileName))]
    [System.Xml.Serialization.XmlElementAttribute("subject", typeof(subject))]
    [System.Xml.Serialization.XmlElementAttribute("target", typeof(target))]
    [System.Xml.Serialization.XmlElementAttribute("threshold", typeof(threshold))]
    [System.Xml.Serialization.XmlElementAttribute("to", typeof(to))]
    [System.Xml.Serialization.XmlElementAttribute("useTransactions", typeof(useTransactions))]
    [System.Xml.Serialization.XmlElementAttribute("username", typeof(userName))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netAppenderTypes type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class appendToFile {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class root {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("appender-ref", typeof(appender_ref))]
    [System.Xml.Serialization.XmlElementAttribute("level", typeof(level))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(param))]
    public object[] Items;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class appender_ref {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class level {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netLevel value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum log4netLevel {
    
    /// <remarks/>
    ALL,
    
    /// <remarks/>
    DEBUG,
    
    /// <remarks/>
    INFO,
    
    /// <remarks/>
    WARN,
    
    /// <remarks/>
    ERROR,
    
    /// <remarks/>
    FATAL,
    
    /// <remarks/>
    OFF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class param {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("param")]
    public param[] param1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class renderer {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string renderingClass;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string renderedClass;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class logger {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("appender-ref", typeof(appender_ref))]
    [System.Xml.Serialization.XmlElementAttribute("level", typeof(level))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(param))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool additivity;
    
    public logger() {
        this.additivity = true;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class commandText {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class evaluator {
    
    /// <remarks/>
    public threshold threshold;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public evaluatorTypes type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class threshold {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netLevel value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum evaluatorTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Core.LevelEvaluator")]
    log4netCoreLevelEvaluator,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class lossy {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class bufferSize {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class domain {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class securityContext {
    
    /// <remarks/>
    public userName userName;
    
    /// <remarks/>
    public password password;
    
    /// <remarks/>
    public domain domain;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public securityContextTypes type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class userName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class password {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum securityContextTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Util.NullSecurityContext")]
    log4netUtilNullSecurityContext,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Util.WindowsSecurityContext")]
    log4netUtilWindowsSecurityContext,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class stringToMatch {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class acceptOnMatch {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class levelMin {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netLevel value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class levelToMatch {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netLevel value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class levelMax {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netLevel value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class loggerToMatch {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class regexToMatch {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class filter {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("acceptOnMatch", typeof(acceptOnMatch))]
    [System.Xml.Serialization.XmlElementAttribute("key", typeof(key))]
    [System.Xml.Serialization.XmlElementAttribute("levelMax", typeof(levelMax))]
    [System.Xml.Serialization.XmlElementAttribute("levelMin", typeof(levelMin))]
    [System.Xml.Serialization.XmlElementAttribute("levelToMatch", typeof(levelToMatch))]
    [System.Xml.Serialization.XmlElementAttribute("loggerToMatch", typeof(loggerToMatch))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(param))]
    [System.Xml.Serialization.XmlElementAttribute("regexToMatch", typeof(regexToMatch))]
    [System.Xml.Serialization.XmlElementAttribute("stringToMatch", typeof(stringToMatch))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netFilterTypes type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class key {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum log4netFilterTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.DenyAllFilter")]
    log4netFilterDenyAllFilter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.LevelMatchFilter")]
    log4netFilterLevelMatchFilter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.LevelRangeFilter")]
    log4netFilterLevelRangeFilter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.LoggerMatchFilter")]
    log4netFilterLoggerMatchFilter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.MdcFilter")]
    log4netFilterMdcFilter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.NdcFilter")]
    log4netFilterNdcFilter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.PropertyFilter")]
    log4netFilterPropertyFilter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Filter.StringMatchFilter")]
    log4netFilterStringMatchFilter,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class priority {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public priorityTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum priorityTypes {
    
    /// <remarks/>
    Normal,
    
    /// <remarks/>
    Low,
    
    /// <remarks/>
    High,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class remotePort {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class remoteAddress {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class localPort {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class pickupDir {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class port {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class smtpHost {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class authentication {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public authenticationTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum authenticationTypes {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    Basic,
    
    /// <remarks/>
    Ntlm,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class to {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class subject {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class commandType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CommandType value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum CommandType {
    
    /// <remarks/>
    Text,
    
    /// <remarks/>
    StoredProcedure,
    
    /// <remarks/>
    TableDirect,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class from {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class staticLogFileName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class rollingStyle {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public rollingStyleTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum rollingStyleTypes {
    
    /// <remarks/>
    Once,
    
    /// <remarks/>
    Size,
    
    /// <remarks/>
    Date,
    
    /// <remarks/>
    Composite,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class maxSizeRollBackups {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class maximumFileSize {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class maxFileSize {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class datePattern {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class countDirection {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public countDirectionTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum countDirectionTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("-1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item11,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sink {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class server {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sender {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class recipient {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class identity {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class facility {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public facilityTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum facilityTypes {
    
    /// <remarks/>
    Kernel,
    
    /// <remarks/>
    User,
    
    /// <remarks/>
    Mail,
    
    /// <remarks/>
    Daemons,
    
    /// <remarks/>
    Authorization,
    
    /// <remarks/>
    Syslog,
    
    /// <remarks/>
    Printer,
    
    /// <remarks/>
    News,
    
    /// <remarks/>
    Uucp,
    
    /// <remarks/>
    Clock,
    
    /// <remarks/>
    Authorization2,
    
    /// <remarks/>
    Ftp,
    
    /// <remarks/>
    Ntp,
    
    /// <remarks/>
    Audit,
    
    /// <remarks/>
    Alert,
    
    /// <remarks/>
    Clock2,
    
    /// <remarks/>
    Local0,
    
    /// <remarks/>
    Local1,
    
    /// <remarks/>
    Local2,
    
    /// <remarks/>
    Local3,
    
    /// <remarks/>
    Local4,
    
    /// <remarks/>
    Local5,
    
    /// <remarks/>
    Local6,
    
    /// <remarks/>
    Local7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class file {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class encoding {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public encodingTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum encodingTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("us-ascii")]
    usascii,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("utf-7")]
    utf7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("utf-8")]
    utf8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("utf-16")]
    utf16,
    
    /// <remarks/>
    unicodeFFFE,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("utf-32")]
    utf32,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("utf-32BE")]
    utf32BE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class machineName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class logName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class applicationName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class immediateFlush {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class foreColor {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public allColorTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum allColorTypes {
    
    /// <remarks/>
    Black,
    
    /// <remarks/>
    Blue,
    
    /// <remarks/>
    Cyan,
    
    /// <remarks/>
    Green,
    
    /// <remarks/>
    HighIntensity,
    
    /// <remarks/>
    Magenta,
    
    /// <remarks/>
    Purple,
    
    /// <remarks/>
    Red,
    
    /// <remarks/>
    White,
    
    /// <remarks/>
    Yellow,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class attributes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public attributesTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum attributesTypes {
    
    /// <remarks/>
    Bright,
    
    /// <remarks/>
    Dim,
    
    /// <remarks/>
    Underscore,
    
    /// <remarks/>
    Blink,
    
    /// <remarks/>
    Reverse,
    
    /// <remarks/>
    Hidden,
    
    /// <remarks/>
    Strikethrough,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class eventLogEntryType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public EventLogEntryType value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum EventLogEntryType {
    
    /// <remarks/>
    Error,
    
    /// <remarks/>
    Warning,
    
    /// <remarks/>
    Information,
    
    /// <remarks/>
    SuccessAudit,
    
    /// <remarks/>
    FailureAudit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class backColor {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public allColorTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class severity {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public severityTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum severityTypes {
    
    /// <remarks/>
    Emergency,
    
    /// <remarks/>
    Alert,
    
    /// <remarks/>
    Critical,
    
    /// <remarks/>
    Error,
    
    /// <remarks/>
    Warning,
    
    /// <remarks/>
    Notice,
    
    /// <remarks/>
    Informational,
    
    /// <remarks/>
    Debug,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mapping {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", typeof(attributes))]
    [System.Xml.Serialization.XmlElementAttribute("backColor", typeof(backColor))]
    [System.Xml.Serialization.XmlElementAttribute("eventLogEntryType", typeof(eventLogEntryType))]
    [System.Xml.Serialization.XmlElementAttribute("foreColor", typeof(foreColor))]
    [System.Xml.Serialization.XmlElementAttribute("level", typeof(level))]
    [System.Xml.Serialization.XmlElementAttribute("severity", typeof(severity))]
    public object[] Items;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class target {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public consoleTargetTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum consoleTargetTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Console.Out")]
    ConsoleOut,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Console.Error")]
    ConsoleError,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class useTransactions {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class reconnectOnError {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class precision {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class base64EncodeMessage {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class conversionPattern {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class base64EncodeProperties {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ignoresException {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class header {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class footer {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class layout {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base64EncodeMessage", typeof(base64EncodeMessage))]
    [System.Xml.Serialization.XmlElementAttribute("base64EncodeProperties", typeof(base64EncodeProperties))]
    [System.Xml.Serialization.XmlElementAttribute("conversionPattern", typeof(conversionPattern))]
    [System.Xml.Serialization.XmlElementAttribute("footer", typeof(footer))]
    [System.Xml.Serialization.XmlElementAttribute("header", typeof(header))]
    [System.Xml.Serialization.XmlElementAttribute("ignoresException", typeof(ignoresException))]
    [System.Xml.Serialization.XmlElementAttribute("key", typeof(key))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(param))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public log4netLayoutTypes type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum log4netLayoutTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Layout.ExceptionLayout")]
    log4netLayoutExceptionLayout,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Layout.PatternLayout")]
    log4netLayoutPatternLayout,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Layout.RawPropertyLayout")]
    log4netLayoutRawPropertyLayout,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Layout.RawTimeStampLayout")]
    log4netLayoutRawTimeStampLayout,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Layout.RawUtcTimeStampLayout")]
    log4netLayoutRawUtcTimeStampLayout,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Layout.SimpleLayout")]
    log4netLayoutSimpleLayout,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Layout.XmlLayout")]
    log4netLayoutXmlLayout,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class scale {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class parameterName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class size {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class dbType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DbType value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum DbType {
    
    /// <remarks/>
    AnsiString,
    
    /// <remarks/>
    Binary,
    
    /// <remarks/>
    Byte,
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    Currency,
    
    /// <remarks/>
    Date,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    Decimal,
    
    /// <remarks/>
    Double,
    
    /// <remarks/>
    Guid,
    
    /// <remarks/>
    Int16,
    
    /// <remarks/>
    Int32,
    
    /// <remarks/>
    Int64,
    
    /// <remarks/>
    Object,
    
    /// <remarks/>
    SByte,
    
    /// <remarks/>
    Single,
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Time,
    
    /// <remarks/>
    UInt16,
    
    /// <remarks/>
    UInt32,
    
    /// <remarks/>
    UInt64,
    
    /// <remarks/>
    VarNumeric,
    
    /// <remarks/>
    AnsiStringFixedLength,
    
    /// <remarks/>
    StringFixedLength,
    
    /// <remarks/>
    Xml,
    
    /// <remarks/>
    DateTime2,
    
    /// <remarks/>
    DateTimeOffset,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class parameter {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dbType", typeof(dbType))]
    [System.Xml.Serialization.XmlElementAttribute("layout", typeof(layout))]
    [System.Xml.Serialization.XmlElementAttribute("parameterName", typeof(parameterName))]
    [System.Xml.Serialization.XmlElementAttribute("precision", typeof(precision))]
    [System.Xml.Serialization.XmlElementAttribute("scale", typeof(scale))]
    [System.Xml.Serialization.XmlElementAttribute("size", typeof(size))]
    public object[] Items;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class connectionType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public connectionTypeTypes value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum connectionTypeTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("System.Data.OleDb.OleDbConnection, System.Data")]
    SystemDataOleDbOleDbConnectionSystemData,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("System.Data.SqlClient.SqlConnection, System.Data")]
    SystemDataSqlClientSqlConnectionSystemData,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Microsoft.Data.Odbc.OdbcConnection, Microsoft.Data.Odbc")]
    MicrosoftDataOdbcOdbcConnectionMicrosoftDataOdbc,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("System.Data.OracleClient.OracleConnection, System.Data.OracleClient")]
    SystemDataOracleClientOracleConnectionSystemDataOracleClient,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("MySql.Data.MySqlClient.MySqlConnection, MySql.Data")]
    MySqlDataMySqlClientMySqlConnectionMySqlData,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class connectionString {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class lockingModel {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public lockingModelTypes type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum lockingModelTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.FileAppender+ExclusiveLock")]
    log4netAppenderFileAppenderExclusiveLock,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.FileAppender+MinimalLock")]
    log4netAppenderFileAppenderMinimalLock,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum log4netAppenderTypes {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.AdoNetAppender")]
    log4netAppenderAdoNetAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.AnsiColorTerminalAppender")]
    log4netAppenderAnsiColorTerminalAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.AspNetTraceAppender")]
    log4netAppenderAspNetTraceAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.BufferingForwardingAppender")]
    log4netAppenderBufferingForwardingAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.ColoredConsoleAppender")]
    log4netAppenderColoredConsoleAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.ConsoleAppender")]
    log4netAppenderConsoleAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.DebugAppender")]
    log4netAppenderDebugAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.EventLogAppender")]
    log4netAppenderEventLogAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.FileAppender")]
    log4netAppenderFileAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.ForwardingAppender")]
    log4netAppenderForwardingAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.LocalSyslogAppender")]
    log4netAppenderLocalSyslogAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.MemoryAppender")]
    log4netAppenderMemoryAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.NetSendAppender")]
    log4netAppenderNetSendAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.OutputDebugStringAppender")]
    log4netAppenderOutputDebugStringAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.RemoteSyslogAppender")]
    log4netAppenderRemoteSyslogAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.RemotingAppender")]
    log4netAppenderRemotingAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.RollingFileAppender")]
    log4netAppenderRollingFileAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.SmtpAppender")]
    log4netAppenderSmtpAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.SmtpPickupDirAppender")]
    log4netAppenderSmtpPickupDirAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.TelnetAppender")]
    log4netAppenderTelnetAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.TextWriterAppender")]
    log4netAppenderTextWriterAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.TraceAppender")]
    log4netAppenderTraceAppender,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("log4net.Appender.UdpAppender")]
    log4netAppenderUdpAppender,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
public enum log4netUpdateAttribute {
    
    /// <remarks/>
    Merge,
    
    /// <remarks/>
    Overwrite,
}
