//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace TXCommons.com.w_99bill.sandbox {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BatchPayWSSoapBinding", Namespace="http://www.99bill.com/apipay/services/BatchPayWS")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(QueryResponseBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PostResponseBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PostRequestBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SimpleResponseBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SimpleRequestBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BankResponseBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BankRequestBean))]
    public partial class BatchPayService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback bankPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback simplePayOperationCompleted;
        
        private System.Threading.SendOrPostCallback postPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryDealOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BatchPayService() {
            this.Url = global::TXCommons.Properties.Settings.Default.TXCommons_com_w_99bill_sandbox_BatchPayService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event bankPayCompletedEventHandler bankPayCompleted;
        
        /// <remarks/>
        public event simplePayCompletedEventHandler simplePayCompleted;
        
        /// <remarks/>
        public event postPayCompletedEventHandler postPayCompleted;
        
        /// <remarks/>
        public event queryDealCompletedEventHandler queryDealCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://compatible.api.seashell.bill99.com", ResponseNamespace="http://www.99bill.com/apipay/services/BatchPayWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("bankPayReturn")]
        public BankResponseBean[] bankPay(BankRequestBean[] input, string username, string ip) {
            object[] results = this.Invoke("bankPay", new object[] {
                        input,
                        username,
                        ip});
            return ((BankResponseBean[])(results[0]));
        }
        
        /// <remarks/>
        public void bankPayAsync(BankRequestBean[] input, string username, string ip) {
            this.bankPayAsync(input, username, ip, null);
        }
        
        /// <remarks/>
        public void bankPayAsync(BankRequestBean[] input, string username, string ip, object userState) {
            if ((this.bankPayOperationCompleted == null)) {
                this.bankPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbankPayOperationCompleted);
            }
            this.InvokeAsync("bankPay", new object[] {
                        input,
                        username,
                        ip}, this.bankPayOperationCompleted, userState);
        }
        
        private void OnbankPayOperationCompleted(object arg) {
            if ((this.bankPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bankPayCompleted(this, new bankPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://compatible.api.seashell.bill99.com", ResponseNamespace="http://www.99bill.com/apipay/services/BatchPayWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("simplePayReturn")]
        public SimpleResponseBean[] simplePay(SimpleRequestBean[] input, string username, string ip) {
            object[] results = this.Invoke("simplePay", new object[] {
                        input,
                        username,
                        ip});
            return ((SimpleResponseBean[])(results[0]));
        }
        
        /// <remarks/>
        public void simplePayAsync(SimpleRequestBean[] input, string username, string ip) {
            this.simplePayAsync(input, username, ip, null);
        }
        
        /// <remarks/>
        public void simplePayAsync(SimpleRequestBean[] input, string username, string ip, object userState) {
            if ((this.simplePayOperationCompleted == null)) {
                this.simplePayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsimplePayOperationCompleted);
            }
            this.InvokeAsync("simplePay", new object[] {
                        input,
                        username,
                        ip}, this.simplePayOperationCompleted, userState);
        }
        
        private void OnsimplePayOperationCompleted(object arg) {
            if ((this.simplePayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.simplePayCompleted(this, new simplePayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://compatible.api.seashell.bill99.com", ResponseNamespace="http://www.99bill.com/apipay/services/BatchPayWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("postPayReturn")]
        public PostResponseBean[] postPay(PostRequestBean[] input, string username, string ip) {
            object[] results = this.Invoke("postPay", new object[] {
                        input,
                        username,
                        ip});
            return ((PostResponseBean[])(results[0]));
        }
        
        /// <remarks/>
        public void postPayAsync(PostRequestBean[] input, string username, string ip) {
            this.postPayAsync(input, username, ip, null);
        }
        
        /// <remarks/>
        public void postPayAsync(PostRequestBean[] input, string username, string ip, object userState) {
            if ((this.postPayOperationCompleted == null)) {
                this.postPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostPayOperationCompleted);
            }
            this.InvokeAsync("postPay", new object[] {
                        input,
                        username,
                        ip}, this.postPayOperationCompleted, userState);
        }
        
        private void OnpostPayOperationCompleted(object arg) {
            if ((this.postPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postPayCompleted(this, new postPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://compatible.api.seashell.bill99.com", ResponseNamespace="http://www.99bill.com/apipay/services/BatchPayWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("queryDealReturn")]
        public QueryResponseBean[] queryDeal(QueryRequestBean input, string username, string ip) {
            object[] results = this.Invoke("queryDeal", new object[] {
                        input,
                        username,
                        ip});
            return ((QueryResponseBean[])(results[0]));
        }
        
        /// <remarks/>
        public void queryDealAsync(QueryRequestBean input, string username, string ip) {
            this.queryDealAsync(input, username, ip, null);
        }
        
        /// <remarks/>
        public void queryDealAsync(QueryRequestBean input, string username, string ip, object userState) {
            if ((this.queryDealOperationCompleted == null)) {
                this.queryDealOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryDealOperationCompleted);
            }
            this.InvokeAsync("queryDeal", new object[] {
                        input,
                        username,
                        ip}, this.queryDealOperationCompleted, userState);
        }
        
        private void OnqueryDealOperationCompleted(object arg) {
            if ((this.queryDealCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryDealCompleted(this, new queryDealCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class BankRequestBean {
        
        private double amountField;
        
        private string bankCardNumberField;
        
        private string bankNameField;
        
        private string creditNameField;
        
        private string descriptionField;
        
        private string kaihuhangField;
        
        private string macField;
        
        private string orderIdField;
        
        private string province_cityField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bankCardNumber {
            get {
                return this.bankCardNumberField;
            }
            set {
                this.bankCardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditName {
            get {
                return this.creditNameField;
            }
            set {
                this.creditNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kaihuhang {
            get {
                return this.kaihuhangField;
            }
            set {
                this.kaihuhangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string province_city {
            get {
                return this.province_cityField;
            }
            set {
                this.province_cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class QueryResponseBean {
        
        private double amountField;
        
        private string dealBeginDateField;
        
        private string dealEndDateField;
        
        private double dealFeeField;
        
        private string dealIdField;
        
        private string dealStatusField;
        
        private string failureCauseField;
        
        private string orderIdField;
        
        private string queryTypeField;
        
        private bool resultFlagField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealBeginDate {
            get {
                return this.dealBeginDateField;
            }
            set {
                this.dealBeginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealEndDate {
            get {
                return this.dealEndDateField;
            }
            set {
                this.dealEndDateField = value;
            }
        }
        
        /// <remarks/>
        public double dealFee {
            get {
                return this.dealFeeField;
            }
            set {
                this.dealFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealStatus {
            get {
                return this.dealStatusField;
            }
            set {
                this.dealStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string failureCause {
            get {
                return this.failureCauseField;
            }
            set {
                this.failureCauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool resultFlag {
            get {
                return this.resultFlagField;
            }
            set {
                this.resultFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class QueryRequestBean {
        
        private string dealBeginDateField;
        
        private string dealEndDateField;
        
        private string dealIdField;
        
        private string orderIdField;
        
        private string queryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealBeginDate {
            get {
                return this.dealBeginDateField;
            }
            set {
                this.dealBeginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealEndDate {
            get {
                return this.dealEndDateField;
            }
            set {
                this.dealEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class PostResponseBean {
        
        private string addressField;
        
        private double amountField;
        
        private double creditChargeField;
        
        private string creditNameField;
        
        private double dealChargeField;
        
        private string dealIdField;
        
        private double debitChargeField;
        
        private string descriptionField;
        
        private string failureCauseField;
        
        private string macField;
        
        private string orderIdField;
        
        private string postcodeField;
        
        private bool resultFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public double creditCharge {
            get {
                return this.creditChargeField;
            }
            set {
                this.creditChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditName {
            get {
                return this.creditNameField;
            }
            set {
                this.creditNameField = value;
            }
        }
        
        /// <remarks/>
        public double dealCharge {
            get {
                return this.dealChargeField;
            }
            set {
                this.dealChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
            }
        }
        
        /// <remarks/>
        public double debitCharge {
            get {
                return this.debitChargeField;
            }
            set {
                this.debitChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string failureCause {
            get {
                return this.failureCauseField;
            }
            set {
                this.failureCauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public bool resultFlag {
            get {
                return this.resultFlagField;
            }
            set {
                this.resultFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class PostRequestBean {
        
        private string addressField;
        
        private double amountField;
        
        private string creditNameField;
        
        private string descriptionField;
        
        private string macField;
        
        private string orderIdField;
        
        private string postcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditName {
            get {
                return this.creditNameField;
            }
            set {
                this.creditNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class SimpleResponseBean {
        
        private double amountField;
        
        private string correctNameField;
        
        private string creditAccountField;
        
        private double creditChargeField;
        
        private string creditContactField;
        
        private string creditNameField;
        
        private string currencyCodeField;
        
        private double dealChargeField;
        
        private string dealIdField;
        
        private double debitChargeField;
        
        private string descriptionField;
        
        private string emailIdField;
        
        private string failureCauseField;
        
        private string macField;
        
        private string mobileField;
        
        private string orderIdField;
        
        private bool resultFlagField;
        
        private string tempAccountField;
        
        private bool unregisterField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string correctName {
            get {
                return this.correctNameField;
            }
            set {
                this.correctNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditAccount {
            get {
                return this.creditAccountField;
            }
            set {
                this.creditAccountField = value;
            }
        }
        
        /// <remarks/>
        public double creditCharge {
            get {
                return this.creditChargeField;
            }
            set {
                this.creditChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditContact {
            get {
                return this.creditContactField;
            }
            set {
                this.creditContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditName {
            get {
                return this.creditNameField;
            }
            set {
                this.creditNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public double dealCharge {
            get {
                return this.dealChargeField;
            }
            set {
                this.dealChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
            }
        }
        
        /// <remarks/>
        public double debitCharge {
            get {
                return this.debitChargeField;
            }
            set {
                this.debitChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                this.emailIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string failureCause {
            get {
                return this.failureCauseField;
            }
            set {
                this.failureCauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public bool resultFlag {
            get {
                return this.resultFlagField;
            }
            set {
                this.resultFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tempAccount {
            get {
                return this.tempAccountField;
            }
            set {
                this.tempAccountField = value;
            }
        }
        
        /// <remarks/>
        public bool unregister {
            get {
                return this.unregisterField;
            }
            set {
                this.unregisterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class SimpleRequestBean {
        
        private double amountField;
        
        private string correctNameField;
        
        private string creditContactField;
        
        private string creditNameField;
        
        private string currencyCodeField;
        
        private string descriptionField;
        
        private string macField;
        
        private string orderIdField;
        
        private string tempAccountField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string correctName {
            get {
                return this.correctNameField;
            }
            set {
                this.correctNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditContact {
            get {
                return this.creditContactField;
            }
            set {
                this.creditContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditName {
            get {
                return this.creditNameField;
            }
            set {
                this.creditNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tempAccount {
            get {
                return this.tempAccountField;
            }
            set {
                this.tempAccountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://complatible.dto.domain.seashell.bill99.com")]
    public partial class BankResponseBean {
        
        private double amountField;
        
        private string bankCardNumberField;
        
        private string bankNameField;
        
        private double creditChargeField;
        
        private string creditNameField;
        
        private double dealChargeField;
        
        private string dealIdField;
        
        private double debitChargeField;
        
        private string descriptionField;
        
        private string failureCauseField;
        
        private string kaihuhangField;
        
        private string macField;
        
        private string orderIdField;
        
        private string province_cityField;
        
        private bool resultFlagField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bankCardNumber {
            get {
                return this.bankCardNumberField;
            }
            set {
                this.bankCardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public double creditCharge {
            get {
                return this.creditChargeField;
            }
            set {
                this.creditChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creditName {
            get {
                return this.creditNameField;
            }
            set {
                this.creditNameField = value;
            }
        }
        
        /// <remarks/>
        public double dealCharge {
            get {
                return this.dealChargeField;
            }
            set {
                this.dealChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
            }
        }
        
        /// <remarks/>
        public double debitCharge {
            get {
                return this.debitChargeField;
            }
            set {
                this.debitChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string failureCause {
            get {
                return this.failureCauseField;
            }
            set {
                this.failureCauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kaihuhang {
            get {
                return this.kaihuhangField;
            }
            set {
                this.kaihuhangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string province_city {
            get {
                return this.province_cityField;
            }
            set {
                this.province_cityField = value;
            }
        }
        
        /// <remarks/>
        public bool resultFlag {
            get {
                return this.resultFlagField;
            }
            set {
                this.resultFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void bankPayCompletedEventHandler(object sender, bankPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bankPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bankPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BankResponseBean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankResponseBean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void simplePayCompletedEventHandler(object sender, simplePayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class simplePayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal simplePayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SimpleResponseBean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SimpleResponseBean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void postPayCompletedEventHandler(object sender, postPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostResponseBean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostResponseBean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryDealCompletedEventHandler(object sender, queryDealCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryDealCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryDealCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResponseBean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResponseBean[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591